# Generated by Django 3.2 on 2022-11-03 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/slider')),
                ('discount_deal', models.CharField(choices=[('HOT DEALS', 'HOT DEALS'), ('New Arraivels', 'New Arraivels')], max_length=100)),
                ('sale', models.IntegerField()),
                ('brand', models.CharField(max_length=200)),
                ('discount', models.IntegerField()),
                ('link', models.CharField(max_length=200)),
            ],
        ),
    ]
