# Generated by Django 3.2 on 2022-11-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221103_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
